# Generated by Django 2.2.26 on 2022-03-23 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_type',
            field=models.CharField(choices=[('H', 'History'), ('S', 'Sport'), ('R', 'Relax'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
