# Generated by Django 2.2.26 on 2022-03-27 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destination', '0002_auto_20220324_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
