# Generated by Django 2.2.26 on 2022-03-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='destination.Destination'),
        ),
    ]
