# Generated by Django 2.2.26 on 2022-03-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_auto_20220327_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
    ]
