# Generated by Django 2.2.26 on 2022-03-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Not good'), (2, '2 - Average'), (3, '3 - Good'), (4, '4 - Very good'), (5, '5 - Excellent')], null=True),
        ),
    ]
