# Generated by Django 2.2.26 on 2022-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_auto_20220328_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Not good'), (2, '2 - Average'), (3, '3 - Good'), (4, '4 - Very good'), (5, '5 - Excellent')], default=1),
            preserve_default=False,
        ),
    ]
